name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:


jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@0407394b9d173dfc9cf5695f9f560fef6d61a5fe # v1.0.20
        with:
          merge-method: SQUASH
          reviewers: |
            ChrisCarini
            bansalsulabh