name: 'Update JetBrains Plugin Platform Version'

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update-jetbrains-plugin-platform-version:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          token: ${{ secrets.PAT_TOKEN_FOR_IJ_UPDATE_ACTION }}

      - uses: ChrisCarini/gh-test-ij-release-update-action@7be2a3fb42d619e134202455ff4044aa6d7e639c # main
        with:
          PAT_TOKEN_FOR_IJ_UPDATE_ACTION: ${{ secrets.PAT_TOKEN_FOR_IJ_UPDATE_ACTION }}
